services:
  - type: web
    name: mattress-store-backend
    env: node
    branch: BibaLuxe
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        sync: false

